//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feedback()
        {
            this.ReplyFeedbacks = new HashSet<ReplyFeedback>();
        }
    
        public int feedback_id { get; set; }
        public int account_id { get; set; }
        public int product_id { get; set; }
        public int genre_id { get; set; }
        public int disscount_id { get; set; }
        public int rate_star { get; set; }
        public System.DateTime create_at { get; set; }
        public string create_by { get; set; }
        public string stastus { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string content { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyFeedback> ReplyFeedbacks { get; set; }
    }
}
