//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oder_Detail
    {
        public int product_id { get; set; }
        public int genre_id { get; set; }
        public int disscount_id { get; set; }
        public int order_id { get; set; }
        public double price { get; set; }
        public string status { get; set; }
        public string transection { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_at { get; set; }
        public string update_by { get; set; }
        public System.DateTime update_at { get; set; }
        public int quantity { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
