//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_LapTrinhWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Feedbacks = new HashSet<Feedback>();
            this.Oder_Detail = new HashSet<Oder_Detail>();
            this.ProductImages = new HashSet<ProductImage>();
        }
    
        public int product_id { get; set; }
        public int genre_id { get; set; }
        public int disscount_id { get; set; }
        public int brand_id { get; set; }
        public string product_name { get; set; }
        public double price { get; set; }
        public long view { get; set; }
        public long buyturn { get; set; }
        public string quantity { get; set; }
        public string status { get; set; }
        public string create_by { get; set; }
        public System.DateTime create_at { get; set; }
        public Nullable<int> Type { get; set; }
        public string update_by { get; set; }
        public System.DateTime update_at { get; set; }
        public string specifications { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Discount Discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oder_Detail> Oder_Detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImage> ProductImages { get; set; }
        public object ImageUpload { get; internal set; }
        public IEnumerable<HttpPostedFileBase> ImageUploadMulti { get; internal set; }
    }
}
